# Generated by Django 4.2.7 on 2023-11-20 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('zalozyciel', models.CharField(max_length=100)),
                ('data_zalozenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna'), ('I', 'Inne')], max_length=1)),
                ('miesiac_dodania', models.IntegerField(default=tk.models.default_month)),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tk.stanowisko')),
                ('wlasciciel', models.ForeignKey(default=tk.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_other_persons', 'Can view other persons')],
            },
        ),
    ]
